swagger: "2.0"
info:
  description: "KKday API for tanslations system"
  version: "1.0.0"
  title: "Katalyst API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "sean.hsu@kkday.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: 127.0.0.1:8000
basePath: "/api"
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json
paths:
  /users/login:
    post:
      description: 'Login API'
      summary: API for user login via email and password
      tags:
      - Users
      operationId: UsersLoginPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        default: application/json
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/loginrequest'
      responses:
        200:
          description: 'login success'
          schema:
            $ref: '#/definitions/loginresponse'
          examples:
            application/json:
              data:
                user_oid: 1
                email: sean.hsu@kkday.com
                name: Sean
                role: Admin
                token: eyJpdiI6ImU1anAzMzRmZnNVSVdFMjhNcjRLcXc9PSIsInZhbHVlIjoicFZVYlA4cTdOZHRBaFJoemV2SERZNjVBanRXYlM3cjZ5RHAyUzNUVEcyN0k2V212MVhPTEQyWXVKVlk2Y0pnUyIsIm1hYyI6IjVmMTU5NjY3NGYwZGY0MGUzNWRjYWM2OGJlNDgyODI4NTUyMzNjYTI0MzVjM2VmYjc3ZGFmMmM0ODg4ODMwOGUifQ==
                created_by: sean.hsu@kkday.com
                updated_by: sean.hsu@kkday.com
                created_at: '2019-06-18T02:59:52.000000Z'
                updated_at: '2019-06-18T02:59:52.000000Z'
              meta:
                status: '0000'
                pagination: null
        401:
          description: 'login fail'
          schema:
            $ref: '#/definitions/loginresponse'
          examples:
            application/json:
              data: null
              meta:
                status: '0401'
                pagination: null
  /users/logout:
    post:
      description: 'Logout API'
      summary: API for user logout
      tags:
      - Users
      operationId: UsersLogoutPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        default: application/json
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/logoutrequest'
      responses:
        200:
          description: 'logout success'
          schema:
            $ref: '#/definitions/logoutresponse'
          examples:
            application/json:
              data:
                null
              meta:
                status: '0000'
                pagination: null
        401:
          description: 'logout fail'
          schema:
            $ref: '#/definitions/logoutresponse'
          examples:
            application/json:
              data: null
              meta:
                status: '0401'
                pagination: null
definitions:
  loginrequest:
    title: 'login request'
    example:
      email: sean.hsu@kkday.com
      password: '123456'
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
  loginresponse:
    title: 'login response'
    type: object
    properties:
      data:
        type: object
        properties:
          user_oid:
            type: integer
          email:
            type: string
          name:
            type: string
          role:
            type: string
          token:
            type: string
          created_by:
            type: string
          updated_by:
            type: string
          created_at:
            type: string
          updated_at:
            type: string
      meta:
        type: object
        properties:
          status:
            type: string
          pagination:
            type: object
  logoutrequest:
    title: 'logout request'
    example:
      email: sean.hsu@kkday.com
    type: object
    properties:
      email:
        type: string
    required:
    - email
  logoutresponse:
    title: 'logout response'
    type: object
    properties:
      data:
        type: object
      meta:
        type: object
        properties:
          status:
            type: string
          pagination:
            type: object
tags:
- name: Users
  description: 'Users API'
